"""Build a short report from actual artifacts; leave missing metrics explicit."""
import json
from pathlib import Path
from support import dump, filehash, read
from evaluation import system_rating_summary
from workflow import source_hash, SYSTEMS, DIMS

def system_table(title, block):
    out=['',title,'','| System | Grounding | Relevance | Safety | Clarity | n |','|---|---:|---:|---:|---:|---:|']
    for name in SYSTEMS:
        row=block[name]
        out.append('| '+name+' | '+' | '.join(f'{row[d]["mean"]:.2f}' for d in DIMS)+f' | {row["n"]} |')
    return out

def main():
    root=Path(__file__).resolve().parents[1]
    b=json.loads((root/'results/predictions.json').read_text());agent=[p for p in b['predictions'] if p['model']=='agent'];idx={p['id']:p for p in agent}
    metricpath=root/'results/final/metrics.json';agreepath=root/'results/final/agreement.json';failpath=root/'results/final/failures.json'
    metrics=json.loads(metricpath.read_text()) if metricpath.exists() else None
    ag=json.loads(agreepath.read_text()) if agreepath.exists() else None
    failures=json.loads(failpath.read_text()) if failpath.exists() else None
    human_path=root/'data/human_ratings.csv'
    mapping_path=root/'review/review_mapping.json'
    human_systems=None
    if human_path.exists() and mapping_path.exists():
        human_systems=system_rating_summary(read(human_path), json.loads(mapping_path.read_text()), DIMS, SYSTEMS)
    lines=['# AmazonHelp support agent: evaluation report','',
    '## Scope and what good means','',
    'The system classifies one incoming customer message, drafts a reply using historical support examples, and states whether a human must review it. Useful replies should address the requested action without inventing refunds, delivery promises or account access. Historical tweets cannot establish current Amazon policy. No transactions, authentication, multi-turn memory or image understanding are implemented. This is an offline experiment, not an Amazon product.','',
    '## Data and evaluation design','',
    'The source is thoughtvector/Customer Support on Twitter. The importer found 76,799 root customer messages with direct AmazonHelp responses. It joins all direct brand replies in timestamp order, removes normalized duplicates and splits whole customers. The fixed sample contains 2,000 training, 80 development and 200 test messages. The original inspected cohort is pinned by tweet ID. Exact matching and shared customers are excluded across splits; semantic paraphrases and missing conversation links remain possible.','',
    'Eight intents came from inspecting 100 training examples: delivery, refund_return, payment, account, product, subscription, feedback and other. Training labels are weak keyword labels unless a human supplies replacements. Test labels are never generated by those rules. The attached workbook collects 200 human intent/escalation labels and 60 blind reply ratings on a matched 20-message cohort. No prediction or reference reply is shown on the gold-label tab.','',
    '## Systems and results','',
    'The trivial baseline predicts the weak-training majority intent and always escalates. The simple baseline uses ordered keywords plus the nearest historical reply, always for review. The agent combines explicit-action rules with TF-IDF nearest-example voting for unmatched messages. It selects exact clarification questions from a small training-only catalog, checks source spans at runtime, and falls back to a topic-specific escalation. Only whole-message social acknowledgements can be auto-handled. Optional LLM drafting is implemented but is not the reported system.','',
    f'The measured offline run generated {len(b["predictions"])} predictions for 200 messages in {b["metadata"]["runtime_seconds"]:.2f} seconds. The agent selected a source-checked training question for {sum(p["draft_source"]=="training_question" for p in agent)} messages and used a generic escalation for {sum(p["draft_source"]=="generic" for p in agent)}. Auto-handling coverage was {sum(p["escalate"]==0 for p in agent)}/200. These are observed system behaviours, not estimates of quality.','']
    if metrics:
        lines+=['| System | Macro-F1 | Intent accuracy | Auto coverage | Unsafe auto rate | Escalation recall |','|---|---:|---:|---:|---:|---:|']
        for name,m in metrics['systems'].items():
            vals=[m[k] for k in ['intent_macro_f1','intent_accuracy','auto_coverage','unsafe_auto_rate','escalation_recall']]
            lines+=['| '+name+' | '+' | '.join('undefined' if v is None else f'{v:.3f}' for v in vals)+' |']
        lines+=['','Per-class scores, confusion matrices, customer-group bootstrap intervals and Wilson intervals are in results/final/metrics.json. Macro-F1 uses all eight fixed labels, assigning zero to an absent class. A separate present-class macro-F1 is also reported. Routing quality is separate from draft quality: every current system escalates all sampled messages, so escalation recall does not distinguish them. Agent and simple 95% bootstrap intervals for macro-F1 both sit near 0.35–0.50; the 0.007 F1 gap is not a reliable improvement. Thirteen gold cases were labelled no-escalate (thanks or praise); the agent still escalated them.','']
    else:
        lines+=['**Human quality results are pending.** Accuracy, F1, escalation correctness and baseline quality comparisons cannot be reported before the 200 examples are hand-labelled. The software refuses to score an incomplete or machine-labelled gold set.','']
    lines+=['## LLM judge and human agreement','',
    'The blind judge uses separate 1–5 rubrics for grounding, relevance, safety and clarity. Each system answering the same message receives the same historical evidence packet. Model identity is excluded. A generic escalation can be safe but irrelevant. Requests are cached by exact case, rubric, endpoint and model, and interrupted runs resume. The agreement harness reports exact agreement, agreement within one point, mean absolute error and quadratic weighted kappa. A constant all-5 rating pair produces undefined kappa, not perfect reliability.','']
    if ag:
        lines+=['| Dimension | Exact agreement | Within one | MAE | Weighted kappa |','|---|---:|---:|---:|---:|']
        for k,m in ag['metrics'].items():
            kappa='undefined' if m['quadratic_weighted_kappa'] is None else f'{m["quadratic_weighted_kappa"]:.3f}'
            lines+=['| '+k+' | '+f'{m["exact_agreement"]:.3f} | {m["within_one"]:.3f} | {m["mean_absolute_error"]:.3f} | '+kappa+' |']
        if ag.get('systems'):
            lines+=system_table('Human mean scores by system (20 matched messages each). Do not hide poor relevance behind high safety.', ag['systems']['human'])
            lines+=system_table('Judge mean scores by system:', ag['systems']['judge'])
        lines+=['','Sixty replies share 20 customer contexts, so agreement is descriptive rather than a population guarantee.','']
    elif human_systems:
        lines+=['A complete 60-reply judge file is not packaged. The HTTPS provider blocked later POSTs from this environment (HTTP 405 or content-filter). Remaining scores were not invented. Reviewers can resume with `python3 src/judge.py`.']
        lines+=system_table('Human mean scores by system (20 matched messages each). Do not hide poor relevance behind high safety.', human_systems)
        lines+=['','The agent is better grounded and safer than copying a nearest historical reply, which can import outdated promises. Its relevance is only slightly above the trivial generic escalation. Safety is not usefulness.','']
    else:
        lines+=['**Judge evidence is pending.** No API credentials were configured and no human reply ratings were supplied. No judge scores or agreement figures have been invented.','']
    lines+=['## Five observed limitations','']
    by_fail={f['id']:f for f in (failures or []) if f['model']=='agent'}
    analyses=[
        ('2652457','Wallet credit falls through keywords into return-like neighbors','The message reports Amazon Pay credit missing from a wallet. It never uses refund, return, cancel, payment, billing, or credit card, so the ordered keyword rules assign other. TF-IDF then votes using nearest training messages, which here are return/cancellation threads, so the draft is a return-or-cancellation escalation. Hypothesis: wallet/balance/credited cases are a payment sublanguage the rules do not cover. Dev check: on development data only, add wallet|balance|credited as payment evidence and measure payment recall against a rise in refund_return false positives. Do not retune on this test tweet.'),
        ('1972845','Process complaints without complaint keywords become other','The customer reports live-chat disconnecting too quickly for a disabled typist. That is a service-process complaint, labelled feedback, but the feedback rule only fires on thanks, thank you, complaint, suggestion, customer service, love, or great. None of those tokens appear, so the classifier stays on other and asks a generic “what is going on?” Hypothesis: many gold-feedback rows are operational complaints, not sentiment words. Dev check: count how many development feedback labels lack those keywords, then try a chat|agent|disconnect|hold pattern on that split only.'),
        ('222856','Entity keywords treat a product suggestion as a billing action','The customer asks for SBI/ICICI cards to join a cashback programme. The human label is feedback with no escalation. The payment rule matches debit inside debit/credit cards, so the agent asks about subscriptions up for renewal. Hypothesis: brand and payment nouns in suggestions are being read as the requested action. Dev check: on development feedback and payment rows, split mentions that co-occur with want/would like/suggestion versus charged/refunded, and measure whether requiring a billing verb cuts this error class.'),
        ('911953','Unresolved orders without shipping vocabulary miss delivery','The customer says an iPhone order is unresolved after mailing the CEO and includes an order id. There is no deliver, ship, parcel, package, tracking, late, or delay token, so the delivery rule never fires and the draft is a generic escalation. Hypothesis: “order not resolved” is a delivery/fulfillment request in this brand’s data even without logistics words. Dev check: among development delivery labels, measure the share that contain order but not the current delivery lexicon, then test adding a bounded order keyword and inspect precision against payment and refund_return.'),
        ('2809446','Exact-thanks auto-handle misses ordinary acknowledgements','Gold is feedback with escalate=0: a routine thanks plus a URL. The auto-handle regex requires the whole message, after stripping [USER], to be thanks, thank you, thanks so much, great, or awesome. “Thanks a lot” and leftover [URL] both fail, so the system escalates and asks what happened. Hypothesis: coverage is near zero because the pattern is a closed phrase list, not “thanks as the only content words.” Dev check: on development escalate=0 rows, measure how many would match if [URL] were ignored and a lot were allowed, and what the unsafe-auto rate would be if that rule were applied only there.'),
    ]
    lines+=['These five cases are agent errors on the human gold set. They are not ranked population frequencies. Rules were not retuned on these test tweets.','']
    for i,(tid,title,note) in enumerate(analyses,1):
        item=by_fail.get(tid) or {'gold_intent':'?','predicted_intent':'?','reply':idx.get(tid,{}).get('reply','')}
        lines+=[f'{i}. **{title} (tweet {tid}; gold {item.get("gold_intent")}, predicted {item.get("predicted_intent")}).** {note} Draft: “{item["reply"]}”','']
    auto=sum(p['escalate']==0 for p in agent)
    headline=('Escalating every message can yield perfect escalation recall and no observed auto-handling errors while automating nothing. In this sample the agent escalates all 200 messages, so unsafe-auto rate is undefined. ' if auto==0 else f'Auto-coverage was {auto}/200. A low unsafe-auto rate can still hide rare high-cost mistakes, and the sample is not representative of unanswered or follow-up traffic. ')
    lines+=['## What is misleading about my headline number?','',
    headline+'Source-span checks prove where a question came from, not that it fits the customer. Root messages with a brand reply exclude unanswered traffic and difficult follow-ups. The sample includes non-English messages and missing-image context. Weak labels share the rule baseline’s biases; a student matching them would not validate quality. One human’s labels and 60 ratings on only 20 messages leave substantial uncertainty. The confidence intervals cannot correct sampling or annotation bias.','',
    '## One more week','',
    'Inspect high-disagreement judge cases and get a second annotator on a random subset. Use development data to distinguish delivery subcases and billing causes, broaden safely answerable informational intents, and calibrate automation coverage against a maximum acceptable error rate. Replace policy-sensitive history with reviewed current support documents. Expand to follow-ups and unanswered messages, audit semantic duplicates, and evaluate on a fresh held-out cohort after any test-informed change.','',
    '## Sources and assistance','',
    'Dataset: Stuart Axelbrooke / thoughtvector, https://www.kaggle.com/datasets/thoughtvector/customer-support-on-twitter (CC BY-NC-SA 4.0). Metric definitions: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html and https://scikit-learn.org/stable/modules/generated/sklearn.metrics.cohen_kappa_score.html . The implementation uses the Python standard library. An AI coding assistant wrote the initial implementation, tests, inspection notes and this report. Human labels and ratings are self-attested by their named reviewers.']
    text='\n'.join(lines)+'\n'
    (root/'docs/report.md').write_text(text)
    words=len(text.split())
    dump(root/'results/final/report_manifest.json',{
        'report_sha256':filehash(root/'docs/report.md'),
        'metrics_sha256':filehash(metricpath) if metricpath.exists() else None,
        'agreement_sha256':filehash(agreepath) if agreepath.exists() else None,
        'predictions_sha256':filehash(root/'results/predictions.json'),
        'code_sha256':source_hash(),
        'word_count':words,
        'metrics_present':bool(metrics),
        'agreement_present':bool(ag),
    })
    print('Report generated; words:',words)

if __name__=='__main__':
    main()
