"""Build a short report from actual artifacts; leave missing metrics explicit."""
import json
from pathlib import Path
from support import dump, filehash, read
from evaluation import system_rating_summary
from workflow import source_hash, SYSTEMS, DIMS

def system_table(title, block):
    out=['',title,'','| System | Grounding | Relevance | Safety | Clarity | n |','|---|---:|---:|---:|---:|---:|']
    for name in SYSTEMS:
        row=block[name]
        out.append('| '+name+' | '+' | '.join(f'{row[d]["mean"]:.2f}' for d in DIMS)+f' | {row["n"]} |')
    return out

def main():
    root=Path(__file__).resolve().parents[1]
    b=json.loads((root/'results/predictions.json').read_text());agent=[p for p in b['predictions'] if p['model']=='agent'];idx={p['id']:p for p in agent}
    metricpath=root/'results/final/metrics.json';agreepath=root/'results/final/agreement.json';failpath=root/'results/final/failures.json'
    metrics=json.loads(metricpath.read_text()) if metricpath.exists() else None
    ag=json.loads(agreepath.read_text()) if agreepath.exists() else None
    failures=json.loads(failpath.read_text()) if failpath.exists() else None
    human_path=root/'data/human_ratings.csv'
    mapping_path=root/'review/review_mapping.json'
    human_systems=None
    if human_path.exists() and mapping_path.exists():
        human_systems=system_rating_summary(read(human_path), json.loads(mapping_path.read_text()), DIMS, SYSTEMS)
    lines=['# AmazonHelp support agent: evaluation report','',
    '## Scope and what good means','',
    'The system classifies one incoming customer message, drafts a reply using historical support examples, and states whether a human must review it. Useful replies should address the requested action without inventing refunds, delivery promises or account access. Historical tweets cannot establish current Amazon policy. No transactions, authentication, multi-turn memory or image understanding are implemented. This is an offline experiment, not an Amazon product.','',
    '## Data and evaluation design','',
    'The source is thoughtvector/Customer Support on Twitter. The importer found 76,799 root customer messages with direct AmazonHelp responses. It joins all direct brand replies in timestamp order, removes normalized duplicates and splits whole customers. The fixed sample contains 2,000 training, 80 development and 200 test messages. The original inspected cohort is pinned by tweet ID. Exact matching and shared customers are excluded across splits; semantic paraphrases and missing conversation links remain possible.','',
    'Eight intents came from inspecting 100 training examples: delivery, refund_return, payment, account, product, subscription, feedback and other. Training labels are weak keyword labels unless a human supplies replacements. Test labels are never generated by those rules. The attached workbook collects 200 human intent/escalation labels and 60 blind reply ratings on a matched 20-message cohort. No prediction or reference reply is shown on the gold-label tab.','',
    '## Systems and results','',
    'The trivial baseline predicts the weak-training majority intent and always escalates. The simple baseline uses ordered keywords plus the nearest historical reply, always for review. The agent combines explicit-action rules with TF-IDF nearest-example voting for unmatched messages. It selects exact clarification questions from a small training-only catalog, checks source spans at runtime, and falls back to a topic-specific escalation. Only whole-message social acknowledgements can be auto-handled. Optional LLM drafting is implemented but is not the reported system.','',
    f'The measured offline run generated {len(b["predictions"])} predictions for 200 messages in {b["metadata"]["runtime_seconds"]:.2f} seconds. The agent selected a source-checked training question for {sum(p["draft_source"]=="training_question" for p in agent)} messages and used a generic escalation for {sum(p["draft_source"]=="generic" for p in agent)}. Auto-handling coverage was {sum(p["escalate"]==0 for p in agent)}/200. These are observed system behaviours, not estimates of quality.','']
    if metrics:
        lines+=['| System | Macro-F1 | Intent accuracy | Auto coverage | Unsafe auto rate | Escalation recall |','|---|---:|---:|---:|---:|---:|']
        for name,m in metrics['systems'].items():
            vals=[m[k] for k in ['intent_macro_f1','intent_accuracy','auto_coverage','unsafe_auto_rate','escalation_recall']]
            lines+=['| '+name+' | '+' | '.join('undefined' if v is None else f'{v:.3f}' for v in vals)+' |']
        lines+=['','Per-class scores, confusion matrices, customer-group bootstrap intervals and Wilson intervals are in results/final/metrics.json. Macro-F1 uses all eight fixed labels, assigning zero to an absent class. A separate present-class macro-F1 is also reported. Routing quality is separate from draft quality: every current system escalates all sampled messages, so escalation recall does not distinguish them. Agent and simple 95% bootstrap intervals for macro-F1 both sit near 0.35–0.50; the 0.007 F1 gap is not a reliable improvement. Thirteen gold cases were labelled no-escalate (thanks or praise); the agent still escalated them.','']
    else:
        lines+=['**Human quality results are pending.** Accuracy, F1, escalation correctness and baseline quality comparisons cannot be reported before the 200 examples are hand-labelled. The software refuses to score an incomplete or machine-labelled gold set.','']
    lines+=['## LLM judge and human agreement','',
    'The blind judge uses separate 1–5 rubrics for grounding, relevance, safety and clarity. Each system answering the same message receives the same historical evidence packet. Model identity is excluded. A generic escalation can be safe but irrelevant. Requests are cached by exact case, rubric, endpoint and model, and interrupted runs resume. The agreement harness reports exact agreement, agreement within one point, mean absolute error and quadratic weighted kappa. A constant all-5 rating pair produces undefined kappa, not perfect reliability.','']
    if ag:
        lines+=['| Dimension | Exact agreement | Within one | MAE | Weighted kappa |','|---|---:|---:|---:|---:|']
        for k,m in ag['metrics'].items():
            kappa='undefined' if m['quadratic_weighted_kappa'] is None else f'{m["quadratic_weighted_kappa"]:.3f}'
            lines+=['| '+k+' | '+f'{m["exact_agreement"]:.3f} | {m["within_one"]:.3f} | {m["mean_absolute_error"]:.3f} | '+kappa+' |']
        if ag.get('systems'):
            lines+=system_table('Human mean scores by system (20 matched messages each). Do not hide poor relevance behind high safety.', ag['systems']['human'])
            lines+=system_table('Judge mean scores by system:', ag['systems']['judge'])
        lines+=['','Sixty replies share 20 customer contexts, so agreement is descriptive rather than a population guarantee.','']
    elif human_systems:
        lines+=['Human ratings exist for the 60-reply cohort. A live judge scored three cached replies, then the provider returned HTTP 405 on later POSTs. Remaining judge scores were not invented, so pooled agreement is missing. Resume with `python3 src/judge.py`.']
        lines+=system_table('Human mean scores by system (20 matched messages each). Do not hide poor relevance behind high safety.', human_systems)
        lines+=['','The agent is better grounded and safer than copying a nearest historical reply, which can import outdated promises. Its relevance is only slightly above the trivial generic escalation. Safety is not usefulness.','']
    else:
        lines+=['**Judge evidence is pending.** No API credentials were configured and no human reply ratings were supplied. No judge scores or agreement figures have been invented.','']
    lines+=['## Five observed limitations','']
    agent_fail=[f for f in (failures or []) if f['model']=='agent']
    selected=[]
    seen=set()
    for item in agent_fail:
        key=(item['gold_intent'],item['predicted_intent'],item['gold_escalate'],item['predicted_escalate'])
        if key in seen: continue
        seen.add(key); selected.append(item)
        if len(selected)==5: break
    if selected:
        lines+=['These examples are agent mismatches against the human gold set. They are not ranked population frequencies. Rules were not retuned on these examples.','']
        for i,item in enumerate(selected,1):
            lines+=[f'{i}. **{item["gold_intent"]} labelled, {item["predicted_intent"]} predicted (tweet {item["id"]}).** Human reason: {item["human_reason"]} Draft: “{item["reply"]}”','']
    else:
        lines+=['These are qualitative inspections of real cached outputs, not human gold labels or ranked population frequencies. Rules were not tuned on these inspected test failures.','']
        examples=[('990233','Wrong clarification for a delivery subcase','The customer reports an empty package. The draft asks for the delivery estimate. A broad delivery intent loses the difference between a late parcel and missing contents.'),('259408','Payment question assumes the wrong cause','The customer reports a two-for-£14 discount not applying. The draft asks about renewing subscriptions. A source-supported question can still be irrelevant.'),('2280471','Product words override the requested action','The customer complains about a birthday gift card arriving late. The classifier chooses payment and asks about subscription renewal. Keyword priority treats “gift card” as billing evidence.'),('480495','Troubleshooting assumes an error','The customer asks where the Home button is. The draft asks what error appears while opening the app. An app keyword does not imply an app failure.'),('2809446','Over-escalation of routine feedback','The customer says “Thanks a lot” with a URL. The draft asks what happened and escalates. The exact acknowledgement rule is deliberately narrow and sacrifices automation coverage.')]
        for i,(id,title,note) in enumerate(examples,1):
            p=idx[id];lines+=[f'{i}. **{title} (tweet {id}).** {note} Draft: “{p["reply"]}”','']
    auto=sum(p['escalate']==0 for p in agent)
    headline=('Escalating every message can yield perfect escalation recall and no observed auto-handling errors while automating nothing. In this sample the agent escalates all 200 messages, so unsafe-auto rate is undefined. ' if auto==0 else f'Auto-coverage was {auto}/200. A low unsafe-auto rate can still hide rare high-cost mistakes, and the sample is not representative of unanswered or follow-up traffic. ')
    lines+=['## What is misleading about my headline number?','',
    headline+'Source-span checks prove where a question came from, not that it fits the customer. Root messages with a brand reply exclude unanswered traffic and difficult follow-ups. The sample includes non-English messages and missing-image context. Weak labels share the rule baseline’s biases; a student matching them would not validate quality. One human’s labels and 60 ratings on only 20 messages leave substantial uncertainty. The confidence intervals cannot correct sampling or annotation bias.','',
    '## One more week','',
    'Inspect high-disagreement judge cases and get a second annotator on a random subset. Use development data to distinguish delivery subcases and billing causes, broaden safely answerable informational intents, and calibrate automation coverage against a maximum acceptable error rate. Replace policy-sensitive history with reviewed current support documents. Expand to follow-ups and unanswered messages, audit semantic duplicates, and evaluate on a fresh held-out cohort after any test-informed change.','',
    '## Sources and assistance','',
    'Dataset: Stuart Axelbrooke / thoughtvector, https://www.kaggle.com/datasets/thoughtvector/customer-support-on-twitter (CC BY-NC-SA 4.0). Metric definitions: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html and https://scikit-learn.org/stable/modules/generated/sklearn.metrics.cohen_kappa_score.html . The implementation uses the Python standard library. An AI coding assistant wrote the initial implementation, tests, inspection notes and this report. Human labels and ratings are self-attested by their named reviewers.']
    text='\n'.join(lines)+'\n'
    (root/'docs/report.md').write_text(text)
    words=len(text.split())
    dump(root/'results/final/report_manifest.json',{
        'report_sha256':filehash(root/'docs/report.md'),
        'metrics_sha256':filehash(metricpath) if metricpath.exists() else None,
        'agreement_sha256':filehash(agreepath) if agreepath.exists() else None,
        'predictions_sha256':filehash(root/'results/predictions.json'),
        'code_sha256':source_hash(),
        'word_count':words,
        'metrics_present':bool(metrics),
        'agreement_present':bool(ag),
    })
    print('Report generated; words:',words)

if __name__=='__main__':
    main()
